# Generated by Django 4.2.16 on 2024-09-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('tg_id', models.IntegerField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(blank=True, max_length=20, null=True)),
                ('events', models.ManyToManyField(related_name='users', to='my_app.event')),
            ],
        ),
    ]
